name:                logout-gtk
version:             0.1.0.0
github:              "githubuser/logout-gtk"
license:             GPL-3
author:              ""
maintainer:          ""
copyright:           ""
description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- directory
- gi-gtk == 3.0.*
- gi-gdk
- gi-gtk-hs
- haskell-gi-base
- process
- unix
- text

library:
  source-dirs: src

executables:
  logout-gtk:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - logout-gtk

tests:
  logout-gtk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - logout-gtk
